language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  
os:
  - linux
  - osx
  - windows
  
matrix:
  allow_failures:
    - os: osx
    - os: linux
# command to run tests
script: pk
